<html>
<head>
<title>TestNG:  Suite_1</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Suite_1</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>11/3/0</td>
</tr><tr>
<td>Started on:</td><td>Tue Sep 17 15:39:00 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (112 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Day1.SoftAssertion.method1()'><b>method1</b><br>Test class: Day1.SoftAssertion</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [11] but found [10],
	expected [hello] but found [Hello]
	at Day1.SoftAssertion.method1(SoftAssertion.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace866918300", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace866918300'><pre>java.lang.AssertionError: The following asserts failed:
	expected [11] but found [10],
	expected [hello] but found [Hello]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Day1.SoftAssertion.method1(SoftAssertion.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>Day1.SoftAssertion@4f933fd1</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method3()'><b>method3</b><br>Test class: Day1.AssertClass_TestNG</td>
<td><div><pre>java.lang.AssertionError: expected [false] but found [true]
	at Day1.AssertClass_TestNG.method3(AssertClass_TestNG.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace974940109", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace974940109'><pre>java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertFalse(Assert.java:65)
	at org.testng.Assert.assertFalse(Assert.java:75)
	at Day1.AssertClass_TestNG.method3(AssertClass_TestNG.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method8()'><b>method8</b><br>Test class: Day1.AssertClass_TestNG</td>
<td><div><pre>java.lang.AssertionError: expected [null] but found [java.lang.Object@d5e576a]
	at Day1.AssertClass_TestNG.method8(AssertClass_TestNG.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1232801781", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1232801781'><pre>java.lang.AssertionError: expected [null] but found [java.lang.Object@d5e576a]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotSame(Assert.java:772)
	at org.testng.Assert.assertNull(Assert.java:708)
	at org.testng.Assert.assertNull(Assert.java:697)
	at Day1.AssertClass_TestNG.method8(AssertClass_TestNG.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Day1.Demo2_TestNG.LogOut()'><b>LogOut</b><br>Test class: Day1.Demo2_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.Demo2_TestNG@d2cc05a</td></tr>
<tr>
<td title='Day1.Demo2_TestNG.Login()'><b>Login</b><br>Test class: Day1.Demo2_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.Demo2_TestNG@d2cc05a</td></tr>
<tr>
<td title='Day1.Demo2_TestNG.Register()'><b>Register</b><br>Test class: Day1.Demo2_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.Demo2_TestNG@d2cc05a</td></tr>
<tr>
<td title='Day1.Demo1_TestNG.f()'><b>f</b><br>Test class: Day1.Demo1_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.Demo1_TestNG@5419f379</td></tr>
<tr>
<td title='Day1.Demo1_TestNG.f1()'><b>f1</b><br>Test class: Day1.Demo1_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.Demo1_TestNG@5419f379</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method1()'><b>method1</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method2()'><b>method2</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method4()'><b>method4</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method5()'><b>method5</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method6()'><b>method6</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
<tr>
<td title='Day1.AssertClass_TestNG.method7()'><b>method7</b><br>Test class: Day1.AssertClass_TestNG</td>
<td></td>
<td>0</td>
<td>Day1.AssertClass_TestNG@7dc7cbad</td></tr>
</table><p>
</body>
</html>